name: Sync upstream
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: sync
        id: sync
        shell: bash
        run: |
          git config --global user.name 'E85Addict'
          git config --global user.email '77761710+E85Addict@users.noreply.github.com'
          git remote add upstream https://github.com/Vendicated/Vencord
          git tag -d $(git tag -l)
          git fetch upstream --tags -f

          C=$(git rev-list --left-right --count origin/main...remotes/upstream/main | awk '{print$2}')
          echo "Ahead $C commits."

          if [ "$C" -gt 0 ]; then
            echo "Rebasing"
            git push origin
            git rebase -X ours upstream/main
            git push --tags -f
            git push -f
          else
            echo "in sync"
          fi

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 9